---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: helloapp
          image: helloAppRegistry.azurecr.io/boot-hello-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: helloapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: helloapp


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloapp-hpa
spec:
  minReplicas: 1  # define min replica count
  maxReplicas: 2 # define max replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloapp
  targetCPUUtilizationPercentage: 75 # target CPU utilization